#!/usr/bin/env python3
"""Generate the WinterTC API assertion and coverage matrix from one table."""

import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
CONTRACT_PATH = REPO_ROOT / "tests" / "wintertc" / "api-surface.json"
TEST_PATH = REPO_ROOT / "tests" / "wintertc" / "api-surface.js"
DOC_PATH = REPO_ROOT / "docs" / "repo" / "wintertc-coverage.md"


def load_contract(path: Path = CONTRACT_PATH) -> dict:
    contract = json.loads(path.read_text(encoding="utf-8"))
    if contract.get("schema_version") != 1:
        raise ValueError("WinterTC API contract must use schema_version 1")
    return contract


def render_test(contract: dict) -> str:
    data = json.dumps(contract, separators=(",", ":"), sort_keys=True)
    return f"""// Generated by scripts/generate_wintertc_surface.py. Do not edit.
const requiredSurface = {data};
const missing = [];
const eventTargetGlobal = typeof globalThis.EventTarget === 'function' &&
  globalThis instanceof globalThis.EventTarget;

for (const item of requiredSurface.interfaces) {{
  if (item.condition === 'event-target-global' && !eventTargetGlobal) continue;
  const constructor = globalThis[item.name];
  if (typeof constructor !== 'function') {{
    missing.push(`${{item.name}} constructor`);
    continue;
  }}
  for (const member of item.static) {{
    if (!(member in constructor)) missing.push(`${{item.name}}.${{member}}`);
  }}
  for (const member of item.prototype) {{
    if (!(member in constructor.prototype)) missing.push(`${{item.name}}.prototype.${{member}}`);
  }}
}}

for (const item of requiredSurface.globals) {{
  if (item.condition === 'event-target-global' && !eventTargetGlobal) continue;
  const path = item.name.split('.');
  let value = globalThis;
  let present = true;
  for (const part of path) {{
    if (value == null || !(part in value)) {{ present = false; break; }}
    value = value[part];
  }}
  if (!present || (item.kind === 'function' && typeof value !== 'function') ||
      (item.kind === 'string' && typeof value !== 'string')) {{
    missing.push(item.name);
  }}
}}

for (const member of requiredSurface.webassembly) {{
  if (!globalThis.WebAssembly || !(member in globalThis.WebAssembly)) {{
    missing.push(`WebAssembly.${{member}}`);
  }}
}}

if (missing.length > 0) {{
  throw new Error(`Missing WinterTC API surface:\n${{missing.join('\\n')}}`);
}}
"""


def _member_text(item: dict) -> str:
    members = [f"`{item['name']}.{name}`" for name in item["static"]]
    members += [f"`{item['name']}.prototype.{name}`" for name in item["prototype"]]
    return ", ".join(members) if members else "Constructor only"


def render_doc(contract: dict) -> str:
    lines = [
        "# WinterTC Coverage Matrix",
        "",
        "Status: active",
        "Last reviewed: 2026-08-01",
        "Owner: theMackabu",
        "",
        f"Source table: `tests/wintertc/api-surface.json` ({contract['snapshot']}).",
        "Regenerate this file and the runtime assertion with",
        "`python3 scripts/generate_wintertc_surface.py`.",
        "A row records coverage; it does not claim that Ant passes the row.",
        "",
        "| TC55 interface | Required members | Behavioral evidence | Documented deviation or gap |",
        "| --- | --- | --- | --- |",
    ]
    for item in contract["interfaces"]:
        lines.append(
            f"| `{item['name']}` | {_member_text(item)} | {item['evidence']} | {item['deviation']} |"
        )
    lines += [
        "",
        "| TC55 global | Kind | Behavioral evidence | Documented deviation or gap |",
        "| --- | --- | --- | --- |",
    ]
    for item in contract["globals"]:
        lines.append(
            f"| `{item['name']}` | {item['kind']} | {item['evidence']} | {item['deviation']} |"
        )
    wasm = ", ".join(f"`WebAssembly.{name}`" for name in contract["webassembly"])
    lines += [
        "",
        "## WebAssembly namespace",
        "",
        wasm,
        "",
        "Behavioral evidence: `wasm/jsapi/**/*.any.js`.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    contract = load_contract()
    TEST_PATH.write_text(render_test(contract), encoding="utf-8")
    DOC_PATH.write_text(render_doc(contract), encoding="utf-8")


if __name__ == "__main__":
    main()
